# Generated by Django 6.0.4 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("quantity", models.PositiveIntegerField(default=1, help_text="Количество единиц товара в корзине.", verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Позиция корзины",
                "verbose_name_plural": "Позиции корзины",
                "ordering": ["id"],
            },
        ),
    ]
