# Generated by Django 6.0.4 on 2026-05-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                help_text="Пользователь, которому принадлежит корзина.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                help_text="Корзина, к которой относится позиция.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                help_text="Товар, добавленный в корзину.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart", "product"], name="cart_item_cart_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(fields=("cart", "product"), name="cart_unique_product_in_cart"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="cart_item_quantity_gt_0"),
        ),
    ]
