# Generated by Django 6.0.4 on 2026-05-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Успешно оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("cancelled", "Отменён"),
                            ("refunded", "Возвращён"),
                        ],
                        default="pending",
                        help_text="Текущий статус платёжной операции.",
                        max_length=32,
                        verbose_name="Статус платежа",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "Банковская карта"), ("cash", "Наличные"), ("sbp", "СБП"), ("other", "Другое")],
                        default="card",
                        help_text="Способ, выбранный пользователем для оплаты заказа.",
                        max_length=32,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Сумма, которую пользователь должен оплатить или оплатил.", max_digits=12, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="RUB", help_text="Валюта платежа в формате ISO 4217, например RUB.", max_length=3, verbose_name="Валюта"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Название платёжного провайдера, например yookassa, tinkoff, sberbank.",
                        max_length=64,
                        verbose_name="Платёжный провайдер",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Внешний идентификатор платежа в системе платёжного провайдера.",
                        max_length=255,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, help_text="Дата и время успешной оплаты.", null=True, verbose_name="Дата оплаты")),
                (
                    "failure_reason",
                    models.TextField(blank=True, help_text="Описание причины неуспешной оплаты, если она известна.", verbose_name="Причина ошибки"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Заказ, к которому относится платёж.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order", "status"], name="payments_order_status_idx"),
                    models.Index(fields=["status", "created_at"], name="payments_status_date_idx"),
                    models.Index(fields=["provider", "provider_payment_id"], name="payments_provider_id_idx"),
                ],
                "constraints": [models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="payments_amount_gte_0")],
            },
        ),
    ]
