[project]
name = "myshop"
version = "0.1.0"
description = ""
authors = [
    {name = "Александр",email = "oxothuk-s@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.4,<7.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "pillow (>=12.2.0,<13.0.0)",
    "django-filter (>=25.2,<26.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)",
    "gunicorn (>=26.0.0,<27.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-django (>=4.12.0,<5.0.0)",
    "coverage (>=7.13.5,<8.0.0)",
    "ruff (>=0.15.12,<0.16.0)",
    "mypy (>=1.20.2,<2.0.0)",
    "django-stubs (>=6.0.3,<7.0.0)",
    "pre-commit (>=4.6.0,<5.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "model-bakery (>=1.23.4,<2.0.0)"
]

[tool.ruff]
line-length = 160
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.local"
pythonpath = [
    "src",
]
python_files = [
    "*tests.py",
    "test_*.py",
    "*_tests.py",
]
testpaths = [
    "tests",
]
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--reuse-db",
    "--cov=.",
    "--cov-report=term-missing",
]
markers = [
    "slow: slow tests",
    "integration: integration tests",
]

[tool.coverage.run]
branch = true
source = [
    ".",
]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "manage.py",
    "config/asgi.py",
    "config/wsgi.py",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
]

[tool.mypy]
python_version = "3.12"
mypy_path = "src"
explicit_package_bases = true
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]
disable_error_code = [
    "arg-type",
    "assignment",
    "attr-defined",
    "method-assign",
    "operator",
    "return-value",
    "var-annotated",
]

[tool.django-stubs]
django_settings_module = "config.settings.local"
