# Generated by Django 6.0.4 on 2026-05-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("rating", models.PositiveSmallIntegerField(help_text="Оценка товара от 1 до 5.", verbose_name="Оценка")),
                ("title", models.CharField(blank=True, help_text="Краткий заголовок отзыва.", max_length=255, verbose_name="Заголовок")),
                ("text", models.TextField(help_text="Основной текст отзыва пользователя.", verbose_name="Текст отзыва")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На модерации"),
                            ("published", "Опубликован"),
                            ("rejected", "Отклонён"),
                            ("hidden", "Скрыт"),
                        ],
                        default="pending",
                        help_text="Статус модерации отзыва.",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, help_text="Признак того, что пользователь действительно покупал товар.", verbose_name="Подтверждённая покупка"
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(blank=True, help_text="Дата и время последней модерации отзыва.", null=True, verbose_name="Дата модерации"),
                ),
                (
                    "moderation_comment",
                    models.TextField(blank=True, help_text="Внутренний комментарий модератора по отзыву.", verbose_name="Комментарий модератора"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Товар, к которому относится отзыв.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
