# Generated by Django 6.0.4 on 2026-05-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, оставивший отзыв.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["product", "status"], name="reviews_product_status_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "created_at"], name="reviews_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rating_idx"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(fields=("user", "product"), name="reviews_unique_user_product"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(condition=models.Q(("rating__gte", 1), ("rating__lte", 5)), name="reviews_rating_between_1_and_5"),
        ),
    ]
