# Generated by Django 6.0.4 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("paid", "Оплачен"),
                            ("processing", "В обработке"),
                            ("shipped", "Отправлен"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="new",
                        help_text="Текущий статус заказа.",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                ("customer_name", models.CharField(help_text="Имя покупателя на момент оформления заказа.", max_length=255, verbose_name="Имя покупателя")),
                (
                    "customer_email",
                    models.EmailField(help_text="Email покупателя на момент оформления заказа.", max_length=254, verbose_name="Email покупателя"),
                ),
                (
                    "customer_phone",
                    models.CharField(help_text="Телефон покупателя на момент оформления заказа.", max_length=32, verbose_name="Телефон покупателя"),
                ),
                ("delivery_address", models.TextField(help_text="Адрес доставки, указанный при оформлении заказа.", verbose_name="Адрес доставки")),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, help_text="Итоговая сумма заказа.", max_digits=12, verbose_name="Итоговая сумма"),
                ),
                ("comment", models.TextField(blank=True, help_text="Комментарий покупателя к заказу.", verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("product_name", models.CharField(help_text="Название товара на момент оформления заказа.", max_length=255, verbose_name="Название товара")),
                ("price", models.DecimalField(decimal_places=2, help_text="Цена товара на момент оформления заказа.", max_digits=12, verbose_name="Цена")),
                ("quantity", models.PositiveIntegerField(help_text="Количество единиц товара в заказе.", verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
                "ordering": ["id"],
            },
        ),
    ]
