# Generated by Django 6.0.4 on 2026-05-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("is_deleted", models.BooleanField(default=False, help_text="Признак мягкого удаления записи.", verbose_name="Удалено")),
                ("deleted_at", models.DateTimeField(blank=True, help_text="Дата и время мягкого удаления записи.", null=True, verbose_name="Дата удаления")),
                ("is_active", models.BooleanField(default=True, help_text="Определяет, доступна ли запись для использования.", verbose_name="Активно")),
                ("name", models.CharField(help_text="Название категории, отображаемое пользователю.", max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(help_text="Уникальный человекочитаемый идентификатор для URL.", max_length=255, unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание категории. Может использоваться на странице категории.", verbose_name="Описание"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Родительская категория для построения дерева категорий.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("is_deleted", models.BooleanField(default=False, help_text="Признак мягкого удаления записи.", verbose_name="Удалено")),
                ("deleted_at", models.DateTimeField(blank=True, help_text="Дата и время мягкого удаления записи.", null=True, verbose_name="Дата удаления")),
                ("is_active", models.BooleanField(default=True, help_text="Определяет, доступна ли запись для использования.", verbose_name="Активно")),
                ("name", models.CharField(help_text="Название товара, отображаемое пользователю.", max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(help_text="Уникальный человекочитаемый идентификатор товара для URL.", max_length=255, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, help_text="Подробное описание товара.", verbose_name="Описание")),
                ("price", models.DecimalField(decimal_places=2, help_text="Текущая цена товара.", max_digits=12, verbose_name="Цена")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Старая цена товара. Может использоваться для отображения скидки.",
                        max_digits=12,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0, help_text="Количество доступных единиц товара.", verbose_name="Остаток на складе")),
                ("sku", models.CharField(help_text="Уникальный артикул товара.", max_length=64, unique=True, verbose_name="Артикул")),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория, к которой относится товар.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи.", verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Дата и время последнего обновления записи.", verbose_name="Дата обновления")),
                ("image", models.ImageField(help_text="Файл изображения товара.", upload_to="products/%Y/%m/%d/", verbose_name="Изображение")),
                (
                    "alt_text",
                    models.CharField(blank=True, help_text="Текстовое описание изображения для SEO и доступности.", max_length=255, verbose_name="Alt-текст"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, help_text="Определяет, является ли изображение главным для товара.", verbose_name="Главное изображение"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Порядок отображения изображения среди других изображений товара.", verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Товар, к которому относится изображение.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_category_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_active", "is_deleted"], name="catalog_category_state_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent", "is_active"], name="catalog_category_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_product_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_product_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "is_deleted"], name="catalog_product_state_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "is_active"], name="catalog_product_category_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(condition=models.Q(("price__gte", 0)), name="catalog_product_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_price__gte", 0), ("old_price__isnull", True), _connector="OR"), name="catalog_product_old_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(condition=models.Q(("stock_quantity__gte", 0)), name="catalog_product_stock_gte_0"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "is_main"], name="catalog_product_image_main_idx"),
        ),
    ]
